### ISSUE TITLE
Is there documentation on what the recommended methods are removed from 0.11? 

### ISSUE THREAD

**Issue by iwyatt** [sarkahn/bevy_ascii_terminal#21]
I'm studying [bevy_roguelike](https://github.com/sarkahn/bevy_roguelike/blob/main/src/ui.rs) implementation of bevy and ascii terminal and I see it uses 0.11.

I see the latest version of bevy_ascii_terminal is 0.14.

Some methods in 0,11 appear not to be implemented in 0.14. draw_progress_bar for example, among many other changes.

Is there a new preferred way to handle these in 0.14 or is the recommendation to only use 0.11? 

For the project, I don't think I need any 0.14 features necessarily, but prefer to use the latest if it makes any notable improvements over previous versions. Are there release notes anywhere for the various versions? 

Thank you for this otherwise excellent plug-in. It has been a lot of fun to work with on this project.

**Comment by sarkahn** [comment]
There's no equivalent for the progress-bar functionality in the newer versions. I felt the "fancy" ui stuff like progress bars and buttons didn't quite fit the "simplicity" of the crate and would be better served in a separate crate at some point which I of course never got around to. With that being said it was all pretty simple so probably not too hard to just copy paste it if you decide to upgrade.

I don't think there's much of a reason for you to upgrade unless you need some newer bevy functionality. Newer versions of bevy_ascii_terminal have mostly just been straight ports to new bevy versions with some minor api changes and a lot of cutting stuff out to try and fit this "simple and easy to use" vision I have in my head.

I had a detailed changelog for a short time but I gave up on since I make so many breaking changes between minor version. I try to detail changes a bit more with some of my bigger git commits but even that is a bit spotty, sorry!

**Comment by iwyatt** [comment]
Thank you!
